export const timezones = [
  { label: "Pacific/Midway (UTC-11:00)", value: "Pacific/Midway" },
  { label: "Pacific/Honolulu (UTC-10:00)", value: "Pacific/Honolulu" },
  { label: "America/Anchorage (UTC-09:00)", value: "America/Anchorage" },
  {
    label: "America/Los_Angeles (UTC-08:00)",
    value: "America/Los_Angeles",
  },
  { label: "America/Denver (UTC-07:00)", value: "America/Denver" },
  { label: "America/Chicago (UTC-06:00)", value: "America/Chicago" },
  { label: "America/New_York (UTC-05:00)", value: "America/New_York" },
  { label: "Atlantic/Bermuda (UTC-04:00)", value: "Atlantic/Bermuda" },
  { label: "America/Sao_Paulo (UTC-03:00)", value: "America/Sao_Paulo" },
  {
    label: "Atlantic/South_Georgia (UTC-02:00)",
    value: "Atlantic/South_Georgia",
  },
  { label: "Atlantic/Azores (UTC-01:00)", value: "Atlantic/Azores" },
  { label: "Europe/London (UTC+00:00)", value: "Europe/London" },
  { label: "Europe/Berlin (UTC+01:00)", value: "Europe/Berlin" },
  { label: "Europe/Athens (UTC+02:00)", value: "Europe/Athens" },
  { label: "Europe/Moscow (UTC+03:00)", value: "Europe/Moscow" },
  { label: "Asia/Dubai (UTC+04:00)", value: "Asia/Dubai" },
  { label: "Asia/Karachi (UTC+05:00)", value: "Asia/Karachi" },
  { label: "Asia/Dhaka (UTC+06:00)", value: "Asia/Dhaka" },
  { label: "Asia/Bangkok (UTC+07:00)", value: "Asia/Bangkok" },
  { label: "Asia/Shanghai (UTC+08:00)", value: "Asia/Shanghai" },
  { label: "Asia/Tokyo (UTC+09:00)", value: "Asia/Tokyo" },
  { label: "Australia/Sydney (UTC+10:00)", value: "Australia/Sydney" },
  { label: "Pacific/Noumea (UTC+11:00)", value: "Pacific/Noumea" },
  { label: "Pacific/Auckland (UTC+12:00)", value: "Pacific/Auckland" },
];
