export const timezones = [
  { label: "Pacific/Midway (UTC-11:00)", value: "Pacific/Midway" },
  { label: "Pacific/Honolulu (UTC-10:00)", value: "Pacific/Honolulu" },
  { label: "America/Anchorage (UTC-09:00)", value: "America/Anchorage" },
  {
    label: "America/Los_Angeles (UTC-08:00)",
    value: "America/Los_Angeles",
  },
  { label: "America/Denver (UTC-07:00)", value: "America/Denver" },
  { label: "America/Chicago (UTC-06:00)", value: "America/Chicago" },
  { label: "America/New_York (UTC-05:00)", value: "America/New_York" },
  { label: "Atlantic/Bermuda (UTC-04:00)", value: "Atlantic/Bermuda" },
  { label: "America/Sao_Paulo (UTC-03:00)", value: "America/Sao_Paulo" },
  {
    label: "Atlantic/South_Georgia (UTC-02:00)",
    value: "Atlantic/South_Georgia",
  },
  { label: "Atlantic/Azores (UTC-01:00)", value: "Atlantic/Azores" },
  { label: "Europe/London (UTC+00:00)", value: "Europe/London" },
  { label: "Europe/Berlin (UTC+01:00)", value: "Europe/Berlin" },
  { label: "Europe/Athens (UTC+02:00)", value: "Europe/Athens" },
  { label: "Europe/Moscow (UTC+03:00)", value: "Europe/Moscow" },
  { label: "Asia/Dubai (UTC+04:00)", value: "Asia/Dubai" },
  { label: "Asia/Karachi (UTC+05:00)", value: "Asia/Karachi" },
  { label: "Asia/Dhaka (UTC+06:00)", value: "Asia/Dhaka" },
  { label: "Asia/Bangkok (UTC+07:00)", value: "Asia/Bangkok" },
  { label: "Asia/Shanghai (UTC+08:00)", value: "Asia/Shanghai" },
  { label: "Asia/Tokyo (UTC+09:00)", value: "Asia/Tokyo" },
  { label: "Australia/Sydney (UTC+10:00)", value: "Australia/Sydney" },
  { label: "Pacific/Noumea (UTC+11:00)", value: "Pacific/Noumea" },
  { label: "Pacific/Auckland (UTC+12:00)", value: "Pacific/Auckland" },
];

interface LabeledLocale {
  value: Intl.LocalesArgument;
  label: string;
}
export const locales: LabeledLocale[] = [
  { value: "af-NA", label: "Afrikaans (Namibia)" },
  { value: "af-ZA", label: "Afrikaans (South Africa)" },
  { value: "af", label: "Afrikaans" },
  { value: "ar-AE", label: "Arabic (United Arab Emirates)" },
  { value: "ar-BH", label: "Arabic (Bahrain)" },
  { value: "ar-DJ", label: "Arabic (Djibouti)" },
  { value: "ar-DZ", label: "Arabic (Algeria)" },
  { value: "ar-EG", label: "Arabic (Egypt)" },
  { value: "ar-EH", label: "Arabic (Western Sahara)" },
  { value: "ar-ER", label: "Arabic (Eritrea)" },
  { value: "ar-IL", label: "Arabic (Israel)" },
  { value: "ar-IQ", label: "Arabic (Iraq)" },
  { value: "ar-JO", label: "Arabic (Jordan)" },
  { value: "ar-KM", label: "Arabic (Comoros)" },
  { value: "ar-KW", label: "Arabic (Kuwait)" },
  { value: "ar-LB", label: "Arabic (Lebanon)" },
  { value: "ar-LY", label: "Arabic (Libya)" },
  { value: "ar-MA", label: "Arabic (Morocco)" },
  { value: "ar-MR", label: "Arabic (Mauritania)" },
  { value: "ar-OM", label: "Arabic (Oman)" },
  { value: "ar-PS", label: "Arabic (Palestine)" },
  { value: "ar-QA", label: "Arabic (Qatar)" },
  { value: "ar-SA", label: "Arabic (Saudi Arabia)" },
  { value: "ar-SD", label: "Arabic (Sudan)" },
  { value: "ar-SO", label: "Arabic (Somalia)" },
  { value: "ar-SS", label: "Arabic (South Sudan)" },
  { value: "ar-SY", label: "Arabic (Syria)" },
  { value: "ar-TD", label: "Arabic (Chad)" },
  { value: "ar-TN", label: "Arabic (Tunisia)" },
  { value: "ar-YE", label: "Arabic (Yemen)" },
  { value: "ar", label: "Arabic" },
  { value: "bg-BG", label: "Bulgarian (Bulgaria)" },
  { value: "bg", label: "Bulgarian" },
  { value: "ca-AD", label: "Catalan (Andorra)" },
  { value: "ca-ES", label: "Catalan (Spain)" },
  { value: "ca-FR", label: "Catalan (France)" },
  { value: "ca-IT", label: "Catalan (Italy)" },
  { value: "ca", label: "Catalan" },
  { value: "cs-CZ", label: "Czech (Czech Republic)" },
  { value: "cs", label: "Czech" },
  { value: "da-DK", label: "Danish (Denmark)" },
  { value: "da-GL", label: "Danish (Greenland)" },
  { value: "da", label: "Danish" },
  { value: "de-AT", label: "German (Austria)" },
  { value: "de-BE", label: "German (Belgium)" },
  { value: "de-CH", label: "German (Switzerland)" },
  { value: "de-DE", label: "German (Germany)" },
  { value: "de-IT", label: "German (Italy)" },
  { value: "de-LI", label: "German (Liechtenstein)" },
  { value: "de-LU", label: "German (Luxembourg)" },
  { value: "de", label: "German" },
  { value: "el-CY", label: "Greek (Cyprus)" },
  { value: "el-GR", label: "Greek (Greece)" },
  { value: "el", label: "Greek" },
  { value: "en-AE", label: "English (United Arab Emirates)" },
  { value: "en-AG", label: "English (Antigua & Barbuda)" },
  { value: "en-AI", label: "English (Anguilla)" },
  { value: "en-AS", label: "English (American Samoa)" },
  { value: "en-AT", label: "English (Austria)" },
  { value: "en-AU", label: "English (Australia)" },
  { value: "en-BB", label: "English (Barbados)" },
  { value: "en-BE", label: "English (Belgium)" },
  { value: "en-BI", label: "English (Burundi)" },
  { value: "en-BM", label: "English (Bermuda)" },
  { value: "en-BS", label: "English (Bahamas)" },
  { value: "en-BW", label: "English (Botswana)" },
  { value: "en-BZ", label: "English (Belize)" },
  { value: "en-CA", label: "English (Canada)" },
  { value: "en-GB", label: "English (United Kingdom)" },
  { value: "en-IN", label: "English (India)" },
  { value: "en-US", label: "English (United States)" },
  { value: "es-AR", label: "Spanish (Argentina)" },
  { value: "es-BO", label: "Spanish (Bolivia)" },
  { value: "es-CL", label: "Spanish (Chile)" },
  { value: "es-CO", label: "Spanish (Colombia)" },
  { value: "es-CR", label: "Spanish (Costa Rica)" },
  { value: "es-EC", label: "Spanish (Ecuador)" },
  { value: "es-ES", label: "Spanish (Spain)" },
  { value: "es-MX", label: "Spanish (Mexico)" },
  { value: "es-PE", label: "Spanish (Peru)" },
  { value: "es-US", label: "Spanish (United States)" },
  { value: "fr-BE", label: "French (Belgium)" },
  { value: "fr-BF", label: "French (Burkina Faso)" },
  { value: "fr-BI", label: "French (Burundi)" },
  { value: "fr-BJ", label: "French (Benin)" },
  { value: "fr-BL", label: "French (Saint Barthélemy)" },
  { value: "fr-CA", label: "French (Canada)" },
  { value: "fr-CH", label: "French (Switzerland)" },
  { value: "fr-FR", label: "French (France)" },
  { value: "it-CH", label: "Italian (Switzerland)" },
  { value: "it-IT", label: "Italian (Italy)" },
  { value: "ja-JP", label: "Japanese (Japan)" },
  { value: "ko-KR", label: "Korean (South Korea)" },
  { value: "nl-NL", label: "Dutch (Netherlands)" },
  { value: "nl-BE", label: "Dutch (Belgium)" },
  { value: "pt-BR", label: "Portuguese (Brazil)" },
  { value: "pt-PT", label: "Portuguese (Portugal)" },
  { value: "zh-CN", label: "Chinese (China)" },
  { value: "zh-HK", label: "Chinese (Hong Kong)" },
  { value: "zh-TW", label: "Chinese (Taiwan)" },
];
